
INSERT INTO JOBPORTAL(ID,COMPANY_NAME,DESGINATION_CODE,SALARY_PROVIDED,EXPERIENCE) VALUES
(1,'NAGARRO','FSD','15 LPA',3),
(2,'IHS MARKIT','SSE','20 LPA',5),
(3,'IMPETUS','SSE','20 LPA',5),
(4,'GOOGLE','FSD','50 LPA',8),
(5,'SAPIENT','SE','14 LPA',3);