DROP TABLE IF EXISTS JOBPORTAL;

CREATE TABLE JOBPORTAL(
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  COMPANY_NAME VARCHAR(250) NOT NULL,
  DESGINATION_CODE VARCHAR(5) NOT NULL,
  SALARY_PROVIDED VARCHAR(250) NOT NULL,
  EXPERIENCE INT NOT NULL
);